language: python
services:
- postgresql
python:
- 2.7
install:
- pip install -r requirements/common.txt
- pip install -r requirements/postgres.txt
before_script:
- cp DMPwerkzeug/test.local.py DMPwerkzeug/local.py
script:
- python manage.py test
