language: python
cache:
  directories:
  - $HOME/virtualenv
services:
- postgresql
- mysql
python:
- 2.7
- 3.4
env:
- DB=postgres
- DB=mysql
- DB=sqlite3
before_install:
  - sudo apt-get install pandoc
install:
- pip install -r requirements/base.txt
- pip install -r requirements/postgres.txt
- pip install -r requirements/mysql.txt
- pip install -r requirements/testing.txt
before_script:
- sh -c "cp testing/settings/testing/$DB.py testing/settings/local.py; fi"
script:
- coverage run manage.py test
after_success:
- coveralls
