language: python
services:
- postgresql
python:
- 2.7
install:
- pip install -r requirements.txt
- pip install psycopg2
before_script:
- cp DMPwerkzeug/test.local.py DMPwerkzeug/local.py
script:
- python manage.py test
