language: python
cache: pip

services:
- postgresql
- mysql

python:
- 2.7
- 3.4
- 3.5
- 3.6

env:
- DB=postgres
- DB=mysql
- DB=sqlite3

before_install:
  - sudo apt-get install -y pandoc texlive-xetex texlive-latex-extra texlive-fonts-recommended

install:
- pip install -e .
- pip install mysqlclient
- pip install psycopg2-binary
- pip install coveralls

before_script:
- sh -c "cp testing/config/settings/$DB.py testing/config/settings/local.py; fi"
- mkdir testing/log

script:
- coverage run testing/runtests.py

after_success:
- coveralls
